import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

//master component
import Layout from "../components/Layout"

//game components
import Stage1 from "../components/Stage1"
import Stage2 from "../components/Stage2"

//react
import { useContext } from "react"

//material-ui
import { Box, Grid, Paper, Typography, Button } from "@mui/material"

//gameState
import { GameContext } from "../components/GameState"

export default function Home() {
  const { selected } = useContext(GameContext)

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box component="main" className="game">
          {!selected ? (
            <>
              {" "}
              <Stage1 />{" "}
            </>
          ) : (
            <>
              {" "}
              <Stage2 />{" "}
            </>
          )}
        </Box>
      </Layout>
    </>
  )
}
